name: CI/CD Workflow

# Déclenchement du workflow sur push ou pull_request
on:
  push:
    branches:
      - main   # Déclenchement sur push vers la branche main
      - develop # Déclenchement sur push vers la branche develop
  pull_request:
    branches:
      - develop # Déclenchement lors d'un PR vers la branche develop

# Définition des jobs du workflow
jobs:
  test:
    runs-on: ubuntu-latest  # Exécution sur la dernière version d'Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupération du code source
    - name: Set up Python
      uses: actions/setup-python@v2  # Configuration de Python
      with:
        python-version: '3.9'  # Version de Python utilisée pour les tests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Mise à jour de pip
        pip install -r requirements.txt  # Installation des dépendances
    - name: Run tests
      run: |
        python -m unittest discover  # Exécution des tests unitaires (unittest)

  deploy:
    runs-on: ubuntu-latest  # Exécution sur la dernière version d'Ubuntu
    needs: test  # Ce job dépend du job 'test', il ne s'exécutera que si les tests passent
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupération du code source
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1  # Utilisation de l'action Netlify pour le déploiement
      with:
        auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Utilisation du token d'authentification secret
        site_id: ${{ secrets.NETLIFY_SITE_ID }}  # ID du site sur Netlify (en variable secrète)
        dir: ./build  # Dossier contenant les fichiers à déployer sur Netlify
